### ISSUE TITLE
[BUG] app event coordinates returned with incorrect values when handling MouseWheel event in GlutWindow

### ISSUE THREAD

**Issue by wyhinton** [fltk-rs/fltk-rs#600]
When handling Event::MouseScroll in a GlutWindow, ```app::event_x()```/```app::event_y()```/```app::event_coords()``` are returning anomalous values. 

Oddly,  calling these event coordinate functions inside other arms of the same ```widg.handle()``` match statement returns the expected results. Push, Drag, and KeyPress all return event coordinates as expected. Note that I have not tested all the different Event types for this issue. 

I thought this might be a quirky FLTK feature at first, but haven't found any notes on such an issue in the FLTK docs. Additionally since the problem only occurs in a GlutWindow, I'm inclined to believe it is a bug.

OS: Windows 10
```
fltk = { version = "0.16", features = ["enable-glwindow"] }
speedy2d = { version = "1.0.7", git = "https://github.com/QuantumBadger/Speedy2D", default-features = true }
gl = "0.14"
```

```lang-rust
use fltk::{
    app,
    enums::Event,
    prelude::{WidgetBase, WidgetExt, GroupExt, WindowExt},
    window::{GlutWindow, Window},
};
use speedy2d::GLRenderer;

fn main() {
    let app = app::App::default();
    let wind_size =  500;
    let mut main_win = Window::new(450,450,wind_size, wind_size, "");
    let mut win = GlutWindow::default().with_size(wind_size, wind_size).with_pos(0,0);
    win.end();
    main_win.end();
    main_win.show();
    win.make_current();

    
    gl::load_with(|s| win.get_proc_address(s));
    let mut renderer = unsafe { GLRenderer::new_for_current_context((wind_size as u32, wind_size as u32)) }.unwrap();

    let mut win_cl = win.clone();
    win.handle(Box::new(move |ev| match ev {
        Event::Push => {
            println!("Pushed");
            dbg!(app::event_x(), app::event_y());
            win_cl.redraw();

            true
        },
        Event::MouseWheel=>{
            println!("Scrolled");
            dbg!(app::event_x(), app::event_y());
            win_cl.redraw();
            false
        }
        _ => false,
    }));
    app.run().unwrap();
}
```
When performing a push, then a scroll in the exact same location, for me, the event coordinate functions are returning different locations. 

```
Pushed
[src\main.rs:27] app::event_x() = 111
[src\main.rs:27] app::event_y() = 359
Scrolled
[src\main.rs:33] app::event_x() = -872
[src\main.rs:33] app::event_y() = -48
```
All the code you need to reproduce it is in here I believe, but I put it into [this ](https://github.com/wyhinton/fltkrsmousescrollissue)repo if that's helpful. Let me know if you can successfully reproduce.

**Comment by MoAlyousef** [comment]
Hi

Yeah I'm able to reproduce but only on Windows. On linux the example works fine.
I think FLTK doesn't accout for the x and y coords of embedded windows on Windows.
I'll recreate a repro in C++ this evening and report it.
For now you can use:
app::event_x_root() - main_win.x()
app::event_y_root() - main_win.y()
To get the required values.

**Comment by eadf** [comment]
Related issue, but not under exactly the same conditions:

If mouse wheels events occur in a de-selected window (selected another window, but hover over fltk window), the `app::event_coords()` are off in a similar fashion.

macOS, fltk 0.16.4

**Comment by MoAlyousef** [comment]
> Related issue, but not under exactly the same conditions:
> 
> If mouse wheels events occur in a de-selected window (selected another window, but hover over fltk window), the `app::event_coords()` are off in a similar fashion.
> 
> macOS, fltk 0.16.4

It seems what you're describing also occurs on linux. FLTK considers the windows x, y coords as zero when getting the event_coords. However it seems consistent for all event types. The outlier being Windows in both issues.

```rust
// modified from above
use fltk::{app, group::*, window::*};

fn main() {
    let app = app::App::default();
    let mut main_win = Window::default().with_size(500, 500);
    let mut sub_win = Window::default().with_size(200, 200).center_of_parent();
    sub_win.set_frame(FrameType::FlatBox);
    sub_win.set_color(Color::Red);
    sub_win.end();
    main_win.end();
    main_win.show();

    sub_win.handle2(move |w, ev| match ev {
        Event::Push => {
            println!("Pushed");
            dbg!(app::event_coords());
            w.redraw();
            true
        },
        Event::MouseWheel=>{
            println!("Scrolled");
            dbg!(app::event_coords());
            w.redraw();
            false
        }
        _ => false,
    });
    app.run().unwrap();
}
```
If one changes the type of sub_win to Group, then it seems the event_coords are those of the main_win, but when sub_win is a Window, then it's all relative to it. 
It seems to be a tricky problem. I haven't ventured into that part of FLTK's sources. I've reported the first issue, for this I'll probably ask for the intended behavior on the fltk general mailing list.

**Comment by MoAlyousef** [comment]
Not yet, but this is the tracker:
https://github.com/fltk/fltk/issues/210

They’re busy releasing version 1.3.6 from what I can gather.

**Comment by Albrecht-S** [comment]
FTR (just a clarification) @MoAlyousef wrote
> If one changes the type of sub_win to Group, then it seems the event_coords are those of the main_win, but when sub_win is a Window, then it's all relative to it.

This is the correct and expected behavior in FLTK. All event coordinates are relative to the window they occur in which can be a subwindow of another window. If you change the inner (Fl_)Window to an (Fl_)Group, then the coordinates are relative to the outer window.

Note: Regarding the mousewheel coordinates (https://github.com/fltk/fltk/issues/210): this is still an open issue, needs to be investigated.

**Comment by eadf** [comment]
> Note: Regarding the mousewheel coordinates (fltk/fltk#210): this is still an open issue, needs to be investigated.
The mouse wheel coordinate issue happens in macOs too, not only in windows (at least for fltk-rs, have not tested fltk)

**Comment by Albrecht-S** [comment]
> The mouse wheel coordinate issue happens in macOs too, not only in windows (at least for fltk-rs, have not tested fltk)

Thanks @eadf, I'm investigating all three major platforms. It's in parts platform-dependent code which doesn't make it easier.

**Comment by Albrecht-S** [comment]
FTR: The underlying bug (fltk/fltk#210) has been fixed. I encourage @MoAlyousef to update fltk-rs and others to test...

**Comment by MoAlyousef** [comment]
Thanks for your effort @Albrecht-S. Unfortunately the issue still persists (tried with the latest master and both C++ and Rust). Looking at the code, I changed the part of the send_event() method:
```cpp
static int send_event(int event, Fl_Widget* to, Fl_Window* window) {
  int dx, dy;
  int old_event = Fl::e_number;
- if (window) {
+ if (window && window->top_window() != window) {
    dx = window->x();
    dy = window->y();
  } else {
    dx = dy = 0;
  }
  for (const Fl_Widget* w = to; w; w = w->parent()) {
    if (w->type() >= FL_WINDOW) {
      dx -= w->x();
      dy -= w->y();
    }
  }
  int save_x = Fl::e_x; Fl::e_x += dx;
  int save_y = Fl::e_y; Fl::e_y += dy;
  int ret = to->handle(Fl::e_number = event);
  Fl::e_number = old_event;
  Fl::e_y = save_y;
  Fl::e_x = save_x;
  return ret;
}
```
Which seems to fix the issue, however I'm not sure if that touches other events in unknown ways.

**Comment by Albrecht-S** [comment]
@MoAlyousef Are you sure you pulled the changes and compiled everything? Please try again, if possible on a fresh checkout. If you used `configure/make`, run `make clean` or `make distclean` before you build FLTK. Unfortunately the dependencies are not always correct in a configure/make build, hence something may be missing in compilation (this is a known issue with configure/make). CMake builds are much more reliable.

That said, I posted a new test and demo program in https://github.com/fltk/fltk/issues/210#issuecomment-873059069. If you are sure you still find issues, please use this demo program and move over to the FLTK issue fltk/fltk#210 for further reports to avoid duplicate discussions. Once we ironed out all issues in FLTK you ought to be able to continue testing/debugging your fltk-rs apps (if this doesn't fix the fltk-rs issue).

If you still find issues with my FLTK/C++ demo program, please report on which platform and provide logs and test instructions. If you need other tests, please feel free to modify the test program and post it to our FLTK issue. Thanks.

**Comment by MoAlyousef** [comment]
Thanks @Albrecht-S, I was thrown off at first by the coordinates of the embedded window. But I can confirm the issue was resolved, and I've pulled the fix to fltk-rs. Thanks again.
A minimal repro with 1.0 syntax:
```rust
use fltk::{
    app,
    enums::{Color, Event},
    prelude::{GroupExt, WidgetBase, WidgetExt},
    window::Window,
};

fn main() {
    let app = app::App::default();
    let mut main_win = Window::default().with_size(500, 500);
    let mut win = Window::default().with_size(400, 400).center_of_parent();
    win.set_color(Color::White);
    win.end();
    main_win.end();
    main_win.show();

    win.handle(move |_, ev| match ev {
        Event::Push => {
            println!("Pushed at {}, {}", app::event_x(), app::event_y());
            true
        }
        Event::MouseWheel => {
            println!("Scrolled at {}, {}", app::event_x(), app::event_y());
            true
        }
        _ => false,
    });

    app.run().unwrap();
}
```

**Comment by MoAlyousef** [comment]
I'll close this issue here and keep the other one opened.
